### ISSUE TITLE
ドラッグ&ドロップによる複数ウィンドウ間のデータソースの移動について

### ISSUE THREAD

**Issue by ji1fhl** [moykeen/supermjo-doc#10]
SuperMjoが複数ウィンドウ存在する状況において，片方のデータソースをもう片方のデータソースペインにドラッグ&ドロップで移動させようとした場合，クラッシュしてしまいます．

クリップボードを介したデータのコピーはできるものの，D&Dでデータの移動ができると大変助かります．
GUI操作図とクラッシュレポートを添付いたしますので，ぜひご対応の検討をお願いします．

OS：macOS Mojave, 10.14.6（18G1012）
Mjo_ver: 0.16.0 (1)

[move_data_via_D&D.pdf](https://github.com/moykeen/supermjo-doc/files/4152090/move_data_via_D.D.pdf)
[crash_report.txt](https://github.com/moykeen/supermjo-doc/files/4152091/crash_report.txt)

**Comment by moykeen** [comment]
了解です。改善に取り組みます。

(意外と難しい・・かも)

**Comment by moykeen** [comment]
できました。
挙動としては、「移動」ではなく「コピー」としたいと思います。

あ、でも普通は移動の挙動にしておいて、Option押しながらドラッグでコピーの方がいいですかね。

まあでもコピーだけが自然ですかね。
例えば、Keynoteでスライドをウィンドウ間でドラッグするとコピーの挙動になる。

**Comment by ji1fhl** [comment]
実装ありがとうございます！

言葉の使い方で誤解を招きました．
欲しかった挙動は「コピー（＆ペースト）」でして，「移動（して元のデータは削除）」ではありませんでした．
ですので「コピー」を普通の挙動としていただければ，そちらの方が嬉しく思います．

**Comment by moykeen** [comment]
本件実装した0.16.1を公開しました。
https://sourceforge.net/projects/mjograph/files/SuperMjograph/SuperMjograph-0.16.1.zip/download
