### ISSUE TITLE
LaTeX表記を用いた場合のレジェンドの大きさについて

### ISSUE THREAD

**Issue by ji1fhl** [moykeen/supermjo-doc#11]
凡例にLaTeX表記を用いた場合，レジェンドの大きさが適切に反映されません．
レジェンドの大きさを適切に調節するような設定が何か必要なのでしょうか？
Wikiを確認しましたが，設定方法がわかりませんでしたので質問させていただきます．
どうぞよろしくお願いいたします．

Mjo_ver: 0.16.0 (1)

[legend.pdf](https://github.com/moykeen/supermjo-doc/files/4152152/legend.pdf)

**Comment by moykeen** [comment]
これはバグです。
Latex文字のサイズをフォントサイズに連動して計算するのを忘れていました。
修正しました。添付のようになります。

次のリリースで反映します。 (近日中の予定)

[legend-rev.pdf](https://github.com/moykeen/supermjo-doc/files/4153909/legend-rev.pdf)

**Comment by moykeen** [comment]
0.16.1で修正反映しました。
https://sourceforge.net/projects/mjograph/files/SuperMjograph/SuperMjograph-0.16.1.zip/download
