### ISSUE TITLE
Super Mjograph最新版

### ISSUE THREAD

**Issue by piyomal3** [moykeen/supermjo-doc#15]
大変お世話になっております．
Super Mjograph-0.17.1の有効期限を過ぎ，使用できなくなりました．
最新版はいつ頃出す予定でしょうか？

**Comment by moykeen** [comment]
すいません、確認します。しばらくお待ちください。

**Comment by moykeen** [comment]
@piyomal3 
最新版をビルドしました。こちら起動できますでしょうか？
https://sourceforge.net/projects/mjograph/files/SuperMjograph/SuperMjograph-0.17.2.zip/download

アプリの公証(Notarization)ができてないのでセキュリティ警告が出ると思いますが、システム環境設定でセキュリティを緩めることで起動できないでしょうか？

**Comment by piyomal3** [comment]
起動できました．誠にありがとうございます．
とても使いやすくて愛用させていただいています．
これからもよろしくお願いいたします．

> @piyomal3 最新版をビルドしました。こちら起動できますでしょうか？ https://sourceforge.net/projects/mjograph/files/SuperMjograph/SuperMjograph-0.17.2.zip/download
> 
> アプリの公証(Notarization)ができてないのでセキュリティ警告が出ると思いますが、システム環境設定でセキュリティを緩めることで起動できないでしょうか？

**Comment by moykeen** [comment]
よかったです。ご確認ありがとうございました。
