### ISSUE TITLE
Data format for error bar and candlestick? 

### ISSUE THREAD

**Issue by WataruOhira** [moykeen/supermjo-doc#7]
I don't know the data format for error-bar and candlestick.
Please let me know that.

**Comment by moykeen** [comment]
candle example:
2019/08/01	3902	3921	3862	3880
2019/07/31	3870	3924	3859	3892
2019/07/30	3890	3998	3874	3944
2019/07/29	3885	3889	3804	3830
2019/07/26	3960	3967	3886	3932
2019/07/25	4035	4064	3964	3977
2019/07/24	4077	4080	4015	4040

The second to fifth columns mean Open, High, Low, Close, respectively.
You can flexibly change this correspondence in "Column Assignment" as show in the attached screenshot.

<img width="1439" alt="candle-demo" src="https://user-images.githubusercontent.com/31440325/62424246-2383b900-b707-11e9-9302-d87f733da146.png">

errorbar example:
1	1	0.1	0.2
2	2	0.1	0.2
3	3	0.2	0.3
4	4	0.2	0.3

The third and forth columns mean stddevX and stddevY, respectively.
As in the candle-stick demo, you can customize column correspondence as you like.


<img width="1315" alt="errorbar-demo" src="https://user-images.githubusercontent.com/31440325/62424248-267ea980-b707-11e9-8a75-89f3497b1720.png">
