### ISSUE TITLE
描画範囲の拡大(ズームアウト)方法について

### ISSUE THREAD

**Issue by Acruxx** [moykeen/supermjo-doc#8]
本日から使い始めましたが、動作が直感的で軽くとても使いやすく感じています。
質問(あるいは改善要望)ですが、Inspector viewのview scale虫眼鏡を使わずに描画範囲を広くするコマンド、あるいは操作方法はありますか？
拡大については範囲ドラッグによる操作で直感的にできますが、縮小についてはFitか片軸虫眼鏡しか見つけられないので少しだけ(x軸y軸合わせて)ズームアウトしたいときに少々使いづらいです。
もし現状で該当する操作がなければ実装をご検討頂けますと幸いです。
マウスホイールバーや⌘ｰ、⌘+などのショートカットキーでx軸y軸合わせた拡大縮小ができればいいなと思っています。
どうぞよろしくお願いいたします。

**Comment by moykeen** [comment]
ありがとうございます。

現状はご認識の通りの動作です。
私は、Undoでズームアウト代わりにすることが多いので、これまであまり気になりませんでしたが、
確かにそのような機能はあった方がいいですね。

実装しますので、次のリリースまでお待ちください。

**Comment by Acruxx** [comment]
早速のお返事ありがとうございます。
実装頂けるとのことで大変助かります。ありがとうございます。

大変勝手とは思いますが、ついでの要望として「軸(描画範囲外)でスクロールするとその軸方向のみの拡大縮小」などもできると便利と思います。こちらは現状のView scale虫眼鏡でもできることですので無くても良いとは思いますが思い立ったので記載させて頂きました。
ご検討・ご対応どうぞよろしくお願いいたします。

**Comment by moykeen** [comment]
本日リリースしたversion-0.16.0で本件対応しました。
https://sourceforge.net/projects/mjograph/files/SuperMjograph/SuperMjograph-0.16.0.zip/download

・ホイールの上スクロールで拡大 / 下スクロールで縮小。MagicMouseと手元にあった古いLogicoolで試し、使用感に問題ないかなと。他のマウスでどうかは自信なし。
・TrackPadの拡大縮小ジェスチャーにも対応
・⌘もしくは⌥を押しながら拡大縮小をすることで、X軸もしくはY軸のみ変化させることが可能 (この振る舞いは従来どおり)
・あと、ショートカット ⌘ +/-での拡大縮小にも対応

軸上でのスクロールでその軸だけズームというのは、ちょっと難しかったのと、なくても良いかなと思ったので今回は見送りました。

**Comment by Acruxx** [comment]
こちら本日ダウンロードしました。
使い勝手がとても良くなりました、ありがとうございました！
また、⌘/⌥での片軸拡大縮小については操作を知らなかったのですがこちらも便利そうで助かりました。
ぜひこれからも開発頑張ってください。

**Comment by moykeen** [comment]
使い勝手改善してよかったです。ありがとうございます。
