### ISSUE TITLE
macOS Catalinaアップデート後の使用について

### ISSUE THREAD

**Issue by ji1fhl** [moykeen/supermjo-doc#9]
いつもSuper Mjographにはお世話になっております，ありがとうございます．

macOS 10.15.3 (Catalina)にアップデートしたところ，本アプリが起動後即時クラッシュするようになってしまいました．
アプリを再ダウンロードしても同様の事象が生じてしまいます．
何卒対応をよろしくお願いします．

[crash_report.txt](https://github.com/moykeen/supermjo-doc/files/4125922/crash_report.txt)

**Comment by moykeen** [comment]
レポートありがとうございます。調査してみますので、しばらくお待ち下さい。

**Comment by moykeen** [comment]
今、手元のマシンをCatalinaにアップデートして試してみたのですが、普通に起動できました。
頂いたクラッシュレポートをよく読んでみようと思いますが、何か思い当たる原因あれば教えて下さい。

**Comment by moykeen** [comment]
クラッシュログを分析してみましが、デフォルト値におかしな値が記録されてしまっている可能性があります。

~/Library/Preferences/ に com.mjo.SuperMjograph.plist
というファイルがあると思いますが、これを削除してみてください。

**Comment by ji1fhl** [comment]
削除してみたところ，正常に起動させることができました．
クラッシュの原因に思い当たることもなかったため，大変安心しております．

ご対応，ありがとうございました．

**Comment by moykeen** [comment]
確認ありがとうございます。直ってよかったです。

↓他に同じ症状の人がいるかもしれないのでメモとして残しておきます。

Behavior: crashes as soon as it launches.
Cause: user defaults may contain invalid values.
Remedy: delete ~/Library/Preferences/com.mjo.SuperMjograph.plist
